# Stage 1: Build stage
FROM node:20-bookworm-slim AS build

RUN apt update && apt install -y python3 g++ build-essential jq
WORKDIR /usr/app
COPY ./app /usr/app
RUN ./install.sh

# Stage 2: Build CLI
FROM node:20-bookworm-slim

RUN apt update && apt install -y jq && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /usr/app
COPY --from=build /usr/app /usr/app
COPY --from=build /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=build /usr/local/bin /usr/local/bin

ENTRYPOINT [ "/usr/local/bin/hopp"]
