# Stage 1: Build stage
FROM node:20-alpine AS build

RUN apk add --no-cache python3 g++ make jq
WORKDIR /usr/app
COPY ./app /usr/app
RUN ./install.sh

# Stage 2: Build CLI Image
FROM node:20-alpine

RUN apk add --no-cache jq bash
WORKDIR /usr/app
COPY --from=build /usr/app /usr/app
COPY --from=build /usr/local/lib/node_modules /usr/local/lib/node_modules
COPY --from=build /usr/local/bin /usr/local/bin
RUN rm -rf /usr/app/tmp /usr/app/logs

ENTRYPOINT [ "/usr/local/bin/hopp"]
